#web: python manage.py collectstatic --noinput; python manage.py run_gunicorn -w 3 -b 0.0.0.0:$PORT
#web: gunicorn meHungry_project.wsgi --log-file -
#web: gunicorn -b 127.0.0.1:8000 meHungry_project.wsgi
web: gunicorn meHungry_project.wsgi -b 0.0.0.0:$PORT
